### ISSUE TITLE
Add page & itemsPerPage params

### ISSUE THREAD

**Issue by 0xJohnnyboy** [Sonicfury/spider-query-builder#1]
```yml
# ./config/packages/api_platform.yaml
collection:
        pagination:
            page_parameter_name: _page
            items_per_page_parameter_name: itemsPerPage
```

Add SpiderParams for pagination, with custom param name for both
